---
abstract: 'Release tests for unused variables'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-UnusedVarsTests
provides:
  Dist::Zilla::Plugin::UnusedVarsTests:
    file: lib/Dist/Zilla/Plugin/UnusedVarsTests.pm
    version: 1.100860
requires:
  Carp: 0
  Dist::Zilla::Plugin::InlineFiles: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Moose: 0
  Scalar::Util: 0
  Test::More: 0.88
  Test::Vars: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-Plugin-UnusedVarsTests
  homepage: http://search.cpan.org/dist/Dist-Zilla-Plugin-UnusedVarsTests/
  repository: http://github.com/hanekomu/Dist-Zilla-Plugin-UnusedVarsTests
version: 1.100860
